name: Building

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download the Repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild

    - name: Uploading artifact
      uses: actions/upload-artifact@v2
      with:
        name: UEFN Unlocker
        path: build/UEFN-Unlocker.dll
        if-no-files-found: error